# Generated by Django 4.2 on 2025-12-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediacontent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_content', to='users.user'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.multimediacontent'),
        ),
        migrations.AddField(
            model_name='contentapprovalworkflow',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approvals', to='users.user'),
        ),
        migrations.AddField(
            model_name='contentapprovalworkflow',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='content.multimediacontent'),
        ),
        migrations.AddField(
            model_name='contentapprovalworkflow',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='multimediacontent',
            index=models.Index(fields=['status'], name='multimedia__status_d99e93_idx'),
        ),
        migrations.AddIndex(
            model_name='multimediacontent',
            index=models.Index(fields=['creator'], name='multimedia__creator_6f8733_idx'),
        ),
        migrations.AddIndex(
            model_name='multimediacontent',
            index=models.Index(fields=['category'], name='multimedia__categor_67ce79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('content', 'version_number')},
        ),
    ]
